### ISSUE TITLE
Support second valve and second controller

### ISSUE THREAD

**Issue by clboles** [vanstinator/raincloudy#22] opened 2018-05-20 04:54 UTC
The integration with Home Assistant and a single valve controller is working great, but I'd love to have my second valve controller be integrated as well.  I need more than four zones, so I picked up an extra valve controller.

I see there was a request made over in the Home Assistant community forum.  I'd be happy to help beta test as well if needed.

Thanks!

**Comment by tchellomello** [comment] 2018-05-21 15:46
@clboles  thanks for your interest on this. Let's definitely add support to it.

**Comment by tchellomello** [comment] 2018-05-22 04:35
@clboles  I was looking at this PR and since I just have one controller I will need your help to reverse engineer this. 

If you look at lines https://github.com/tchellomello/raincloudy/blob/master/raincloudy/core.py#L97-L108, you will the piece of code that finds the controller serial and faucet serial so then we can initialize the `RainCloudyController` object. 

What we will need is to parse the HTML and to see how that is presented when 2 controllers are reported. 

You can find that by doing something like: 

```python
from raincloudy.core import RainCloudy
from raincloudy.helpers import serial_finder
r = RainCloudy('username', 'password')
r
<RainCloudy: 123456789>
```
This will load the component and display only 1 controller and 1 faucet (as currently supported), however, you might have the HTML object saved as `r.html` so then let's see if we can other controllers/faucets. In your case, do you have multiple controllers or 2 different faucet connected on the same controller/bridge? 

```python
print(r.html)

serial_finder(r.html['home'])
{'controller_serial': '123456789', 'faucet_serial': ['999999']}
```

Of course, this function `serial_finder` is considering only one controller, but if you inspect the `r.html` manually, do you see any other information or how can we track that? https://github.com/tchellomello/raincloudy/blob/master/raincloudy/helpers.py#L16-L48

Try searching manually by `controller_serial` and `faucet_serial` so then we can see how they will be displayed.  Currently the way it is presented is via Ajax script as showed below: 

```javascript
// AJAX: on a regular interval update all elements, currently every 15 seconds
$( document ).ready(function() {
    setInterval(function () {
                Dajaxice.webserver.get_cu_and_fu_status(Dajax.process, {'controller_serial': '123456789', 'faucet_serial': '999999'});
            }, 15000)
```

That will be our first step to address this problem.  

Thanks for your assistance @clboles

**Comment by clboles** [comment] 2018-05-22 13:03
Sure I'll take a look as soon as I can.  I have a single controller with two valve units.

**Comment by clboles** [comment] 2018-05-22 17:15
I took a quick look, and both faucet serials do not appear to be available in a single page.  There is a combobox where the user selects the valve unit to be displayed.  It is defined with this div:

```
<div class="valveunit">
  <select name="select_faucet" class="simpleselect" id="id_select_faucet" onchange="submit()">
    <option selected="selected" value="0">Front</option>
    <option value="1">Back</option>
  </select>
</div>
```

While auto-discovery would be ideal, I wonder if a simple fallback would be to allow the controller and faucet serials to be entered in the configuration.yaml for the raincloud component.

```
raincloud:
  username: !secret raincloud_username
  password: !secret raincloud_password
  - controller_id: !secret …
    - faucet_id: !secret …
    - faucet_id: !secret …
```

**Comment by tchellomello** [comment] 2018-05-23 22:31
@clboles  thanks for providing this information. 

@clboles  could you please save the  `r.html` contents to a file (please remove any personal information) and send to me so then I can try parse it? Also would be nice to see the `r.html` for each faucet so then we will know what to expect.  You can initialize the object manually once you know the `controller_serial` and the `faucet_serial`. 

```python
from raincloudy.controller import RainCloudyControler
r1 = RainCloudyController(r, 'controller_id', 'faucet_id')
r2 = RainCloudyController(r, 'controller_id', 'faucet_id')
```

Then having the `r.html`, `r1.html` and `r2.html` I think we can parse and test add support to 2 devices. 

You can email me the HTMLs files if you prefer. 

mmello

**Comment by shafty80** [comment] 2018-06-02 20:06
I finally will get both devices on Monday.

I will have two controllers and two valves. I purchased two kits.

**Comment by shafty80** [comment] 2018-06-07 04:35
I have my units installed. 1 controller, 2 valve units.
Named valve units east and west, each faucet back 1 or front 1 etc.

Everything is setup and working great in the melnor app.

Added raincloud, sensor, binary sensor and switch to hassio as per component instructions.

In hassio I haven't group anything or written any automation yet.

I can only see the 4 faucets on West, nothing on East. I do see east west status and east west battery, but they are combined.

Let me know what I can do to help make this work.

**Comment by shafty80** [comment] 2018-06-12 16:22
I have another question.

I have two valves and two controllers.

Would it not be possible to setup two accounts to make it work in hassio?

Thanks

**Comment by tchellomello** [comment] 2018-06-12 17:16
Hello @shafty80, 

   Are you using just 1 username/password to manage them? 
 
   If so, could you please share the information as requested https://github.com/tchellomello/raincloudy/issues/22#issuecomment-390859879 so then we can see how to proceed? 

Thanks

**Comment by shafty80** [comment] 2018-06-12 17:39
I have one username/password.
One controller
Two valves.

Using hassio...

Noob here... What do I do to get you that info? Been a long time since I've done anything on Linux.

Thanks

**Comment by ghostandthemachine** [comment] 2018-07-11 16:23
Hey folks. Thanks @tchellomello for putting this project together. I also have two control units and two valves and want to fully support this. I think I only need one controller for the both valves but it would be great if RainCloudy could just control whatever combination of controllers and valves.

After cloning and looking into things a bit I think we're gonna need to consider a couple things. As @tchellomello explained, `serial_finder` is currently regex matching on script tags then pulling the current control id and valve id from a JSON object. I think this won't scale for this problem though as these are essentially the "current" ids. We can pretty easily determine if more then one controller are available from an account by inspecting the controller select options. A given config page then will make the controllers available through the controller select. This will only show valves for the current controller though.

What I'm wanting to try (admittedly a bit hacky) is to just make num_controllers * num_vavles_per_controller posts and accumulate all controller and valve ids. I think with these we could then have all that's needed to control anything we want. I would then propose to just update the relevant classes to have `raincloudy.controllers` as an array and `controller.faucets` as an array. After that I think most of the code stays the same.

So, if this sounds reasonable as a first crack, @tchellomello can you give anymore info on the form data being posted? I think I will need to just post that form a number of times incrementing the controller and valve units. I can't intercept the browser post to see the form data though and am not sure from the project code. If posting these forms is gonna be the way to get and set data it might be nice to make a helper fn for building this form.

**Comment by ghostandthemachine** [comment] 2018-07-11 19:08
Alternatively the user could just use the serials off of the actual units which are the same as what's being scraped... Not as plug and play though obviously.

**Comment by tchellomello** [comment] 2018-07-19 02:23
Hello @ghostandthemachine, sorry life has been busy for me lately and I just got to your update now. 

I'm down to both ways. Whatever is easy to implement and works fine, let's do it. 

Basically as I was studying the project, we have to pass the controller_id via param to the post request. So if we follow the same workflow, all we need to do is to get a JSON mapping for the controller_id and faucets and that would do the trick. 

I unfortunately just have 1 controller so it's a little bit tricky for me to implement that, but I could help as much as you want to get that working in the library.

**Comment by Guyanthalas** [comment] 2018-07-23 03:52
I don't know how much help you are looking for with this particular project, but I just got my second valve and didn't realize it wasn't supported! Will gladly test anything needed to be tested, although I'd need some basic guidance.

Did the HTML data ever get to you that you requested in the early posts?

**Comment by shafty80** [comment] 2018-08-07 19:03
@tchellomello any progress update?

I'm not much of a coder.... Can do anything with a little directions. Would it help it I sent you a second valve?

**Comment by vanstinator** [comment] 2019-04-05 16:52
bumping a dead thread:

@shafty80 I'm going to try to get this working in a future release but I need a second valve and/or controller. If you're still open to sending one out I can start working on this after my current PR gets merged.

**Comment by shafty80** [comment] 2019-04-05 19:36
@vanstinator I have an extra controller

**Comment by vanstinator** [comment] 2019-04-05 19:38
Great. Once I've got the integration with HA working again we can touch-base.

**Comment by vanstinator** [comment] 2019-04-09 21:00
This is the next major feature on the roadmap. I'm hoping to ship it with raincloudy `0.1.0` with a Home Assistant release sometime after. @shafty80 if you're still willing to part with your extra valve let's coordinate so I have a test device.

Still looking for a second controller unit as well. I'll do what I can without one but I'd always prefer something to test with.

**Comment by shafty80** [comment] 2019-04-19 19:30
@vastinator

I have  an extra controller, unit inside the house.

I don't mind buying the other component for you to get this working. In a trade to learn a little how this is done.

Thanks

**Comment by vanstinator** [comment] 2019-04-24 18:47
@shafty80 I'd be happy to show you how this all works together. Feel free to send me an email so we can coordinate.

**Comment by gerliczky** [comment] 2019-04-26 04:14
Hi @vanstinator,
I have one controller and two valve units. I have some skills in programming, so maybe I could help you in the implementation. Is there any existing branch for that? I see only this which can have some relation [2nd_controller](https://github.com/tchellomello/raincloudy/tree/2nd_controller), but it does not seem to be active.
We can keep contact in email as well if you think I could help here.
I am using HomeAssistant and my goal is to push this feature there.

**Comment by vanstinator** [comment] 2019-05-02 00:25
@gerliczky I've secured a second controller unit. This will probably get me most of the way towards a working implementation. The existing branch is an older branch that is currently stale. I'm starting from scratch. I'll definitely need some help testing the branch when the time comes and I'll let you know when that is. Thanks for reaching out!

**Comment by vanstinator** [comment] 2019-05-15 02:43
I've begun development of the enhancement. @shafty80 was kind enough to donate a 2nd controller to the cause. I only have a single valve so what I'm able to test myself will be rather limited. But I'll provide a beta release of the HA component when it's ready for testing

**Comment by JangoBritt** [comment] 2019-07-11 13:47
am I correct, that I cannot even add the first of my two controllers to my Home-Assistant, if this isn't working?

currently, when trying to add RainCloud to hassio, I get a 500 Server Error when trying to connect to https://wifiaquatimer.com/get_cu_and_fu_status?controller_serial=[s/n removed]&faucet_serial=[s/n removed]%0A2

I guess that's because the _get_cu_and_fu_status is trying to pass an array of two valves, rather than just the single valve?

Would a quick duct-tape job be to change this so that it passed self.faucet[0].serial instead? that'd at least get the first valve through the door?

**Comment by NoahJaehnert** [comment] 2019-07-11 14:38
> currently, when trying to add RainCloud to hassio, I get a 500 Server Error when trying to connect to [https://wifiaquatimer.com/get_cu_and_fu_status?controller_serial=[s/n](https://wifiaquatimer.com/get_cu_and_fu_status?controller_serial=%5Bs/n) removed]&faucet_serial=[s/n removed]%0A2

I'm having the exact same issue with the addition of %0A2 to my first valve as well. I provided my feedback here: https://github.com/tchellomello/raincloudy/issues/41#issuecomment-509028266

Looking forward to getting this fixed. I currently have one controller and two valves set up/configured in my account. I also own an additional controller and two valves, for a total of two controllers, four valves. 

Happy to help test/debug however I can. Just let me know!

**Comment by bdwilson** [comment] 2020-05-13 00:32
FYI, the original author is looking for a home for this as he no longer owns the devices he developed this for.  Anyone have this working with multiple controllers & valves, or even multiple valves.

**Comment by shafty80** [comment] 2020-05-13 00:41
Is anyone still working on this? Melnor sent me a new controller as they had a recall and I also have a new valve on the way as the other broke.

I would like to see this working one day and would like to know how I can help. Been doing more coding lately, still learning and willing to help. 

Thanks

**Comment by bdwilson** [comment] 2020-05-13 00:46
I wrote a really crummy flask app to take API calls from Hubitat (https://github.com/bdwilson/rainycloud-flask) and (https://github.com/bdwilson/hubitat/blob/master/Raincloud/Raincloud.groovy) but could really use a version that suppotts multiple valves and controllers.

**Comment by gerliczky** [comment] 2020-05-13 04:17
That's great @bdwilson. If you need help in development or testing, please let me know. I own a controller (replaced at the recall procedure)  and two valve units. I would be really happy if I could use them in HA.

**Comment by vanstinator** [comment] 2020-05-16 19:04
I've got mine out of storage for the year and just discovered the recall.
Once I have working units I'll likely revisit my PR as the devices are more
integral to my gardening setup than they were last year.

**Comment by harryohalloran** [comment] 2020-05-17 18:49
@vanstinator, I have my two valves and one controller ready to go if you need me to test sooner rather than later.  I typically connect it through Hassio but if you can walk me through getting the code in a state where I can test now, I'm happy to.

**Comment by vanstinator** [comment] 2020-05-18 13:11
I started dusting off the branch last night and got it all running locally.

I'm not entirely sure if the path forward is without obstacle. The Home Assistant team recently decided to deprecate integrations that rely on web scraping. I might be able to update the default integration yet. But there's a chance it gets rejected. If that happens I'm planning on releasing the integration as a custom integration on [HACS](https://hacs.xyz/). (Long term I may do this anyway so next time Melnor makes a breaking change I can get a fix out without waiting for a Home Assistant release).

**Comment by gerliczky** [comment] 2020-05-18 13:14
Sounds good! Thanks for your effort @vanstinator! If you need help in testing, please let me know.

**Comment by harryohalloran** [comment] 2020-05-18 13:17
@vanstinator, if you have a way that I can just throw the updates in a custom component for home assistant to help test, let me know how and I can get on it ASAP.

**Comment by vanstinator** [comment] 2020-05-18 13:23
@harryohalloran once I get this library completely sorted yes that should be possible. In fact if I just release on HACS right away that would facilitate easier beta testing.

**Comment by JangoBritt** [comment] 2020-05-18 13:53
poised and ready to assist with testing

**Comment by vanstinator** [comment] 2020-05-21 00:48
The build is passing and locally I'm getting happier with the library. I'll _likely_ release a 1.0a1 build sooner rather than later. This build will be the core of the HACS release of the Raincloud integration that will include multi valve and multi controller support.

**Comment by vanstinator** [comment] 2020-05-22 00:18
I have a repo with HACS set up here https://github.com/vanstinator/hass-raincloud

There will soon be a beta track that contains initial versions of the multi-controller and multi-valve units

**Closed as completed** 2020-05-22 00:28 UTC
Labels: enhancement, help wanted

**Comment by vanstinator** [comment] 2020-05-22 03:12
The early access release in Home Assistant is now available. There are a few known issues that will be addressed in future alpha builds before this goes to stable.

https://github.com/vanstinator/hass-raincloud/releases/tag/1.0.0-alpha.1

**Comment by gerliczky** [comment] 2020-05-22 10:30
Could you please instruct me how could I try this alpha release out?

**Comment by vanstinator** [comment] 2020-05-22 11:36
The easiest way is to use the Home Assistant Community Store to sideload and keep custom components up-to-date.

https://hacs.xyz/

Once you have the store configured in your Home Assistant instance you can add my `hass-raincloud` repo as a custom repo inside HACS.

In the future the integration will be available directly in the HACS store without adding a custom repo.

**Comment by gerliczky** [comment] 2020-05-22 12:50
Thanks @vanstinator. I managed to do the configuration. It works flawlessly. :) (I tried to add the repository on the Supervisor site before, that was my mistake.)
I will let you know once I experiency any bug or malfunction.

**Comment by vanstinator** [comment] 2020-05-22 12:51
Excellent! going forward if you have issues please open then in the `hass-raincloud` repo.
